In [14]:
print("Techcareer - Veri Bilimine Giriş Ders 3")

Techcareer - Veri Bilimine Giriş Ders 3


In [6]:
import numpy as np
import time

def python_version():
  start_time = time.time()
  A = list(range(10000000))
  B = list(range(10000000))
  C = [A[i] + B[i] for i in range(len(A))]
  end_time = time.time()
  sure = end_time - start_time
  print(sure)


def numpy_version():
  start_time = time.time()
  A = np.arange(100000000)
  B = np.arange(100000000)
  C = A + B
  end_time = time.time()
  sure = end_time - start_time
  print(sure)


In [32]:
python_version()  ##Python'da her türlü fonksiyon ve kütüphane çalıştığı için daha yavaş

3.1265761852264404


In [33]:
numpy_version   ##Numpy sadece sayısal kısımlar için hazırlandığından optimize çalışıyor

1.218519926071167


In [7]:
list01 = [1,2,3,4,5]
arr1 = np.array(list01)
arr1

array([1, 2, 3, 4, 5])

In [8]:
a = np.arange(1,25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [10]:
a = np.arange(0,151,25)
a

array([  0,  25,  50,  75, 100, 125, 150])

In [11]:
#Sıfırlardan oluşan bir dizi için
zeros = np.zeros(10).astype(int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
ones = np.ones(8).astype(int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
#repeat(sayi, tekrar sayisi)
sekizler = np.repeat(8, 10)
sekizler

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [15]:
dizi = np.array([1,3,5,7,9])
deneme1 = np.repeat(dizi,3)
deneme1

array([1, 1, 1, 3, 3, 3, 5, 5, 5, 7, 7, 7, 9, 9, 9])

In [18]:
sayidizi = np.arange(1,21)
tekler = sayidizi[sayidizi % 2 == 1]
tekler

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
#Linspace(baslangic, bitis, adet) fonksiyonu, başlangıçtan bitişe kadar  adet kadar eşit uzaklıkta böler
lns = np.linspace(20,30,3).astype(int)
lns

array([20, 25, 30])

In [22]:
np.random.random(4)

array([0.41854975, 0.93660613, 0.53384284, 0.3729843 ])

In [25]:
np.random.randint(100,350,10)

array([314, 321, 308, 160, 193, 153, 125, 279, 246, 139], dtype=int32)

In [26]:
#Normalde random sayı üretilirken bilgisayarın saati referans alınır.
#Biz random.seed(sayi) fonksiyonu ile başlangıç değerine bir sayi atarız. Eğer aynı değer iki defa kullanılırsa aynı sayılar oluşturulur

np.random.seed(200)
np.random.randint(100,350,10)

array([126, 205, 116, 168, 142, 283, 176, 179, 189, 114], dtype=int32)

In [29]:
np.random.seed(200)
np.random.randint(100,350,10)

array([126, 205, 116, 168, 142, 283, 176, 179, 189, 114], dtype=int32)

In [30]:
a = np.random.randint(200,400,15)
a

array([385, 289, 339, 334, 242, 256, 201, 207, 251, 355, 343, 329, 223,
       285, 352], dtype=int32)

In [31]:
a.max()

np.int32(385)

In [32]:
a.min()

np.int32(201)

In [33]:
a.sum()

np.int64(4391)

In [34]:
a.mean()

np.float64(292.73333333333335)

In [35]:
#Standart sapma
a.std()

np.float64(57.70900180118253)

In [37]:
d = np.arange(1,21)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
#Dizi içerisinde çift sayılar yerine 5 yazan kod
r = np.where(d %2 == 0, 5, d)
r

array([ 1,  5,  3,  5,  5,  5,  7,  5,  9,  5, 11,  5, 13,  5, 15,  5, 17,
        5, 19,  5])

In [40]:
#Dizide boş var mı?  Eğer dizide [1,2,3, np.nan, 4,5] diye değerler olsaydı [F,F,F, T, F,F] yazacaktı
np.isnan(r)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [11]:
sayidizi2 = np.arange(1,21)
sayidizi2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
sayidizi3 = np.arange(10,21)
sayidizi3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
#İki dizi arasındaki farkları görmek için np.setdiff1d(dizi1, dizi2)
np.setdiff1d(sayidizi2,sayidizi3)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#Verileri ters sıralama
sayidizi3[::-1]  

#ya da np.flip(sayidizi3)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [15]:
#reshape() fonksiyonu, oluşturulan diziyi istediğimiz gibi ayarlatır.
resp = np.arange(1,101).reshape(10,10)     #10x10'luk dizi şeklinde ayarlatır
resp

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [16]:
#np.multiply() fonksiyonu dizi içerisinde çarpma yapar.  Normalde sayidizi4 * sayidizi3 komutu da aynısını yapardı.
sayidizi4 = np.arange(20,31)
np.multiply(sayidizi4,sayidizi3)

array([200, 231, 264, 299, 336, 375, 416, 459, 504, 551, 600])

In [17]:
filtrelenmis = resp[resp>50]
filtrelenmis

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
#Birim matris (identity)
I = np.eye(8).astype(int)
I

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [21]:
#Diagonal matris
D = np.diag(np.arange(1,11))
D

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [22]:
D1 = np.diag([3,5,7,9])
D1

array([[3, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])

In [34]:
M1 = np.random.randn(5,5).astype(int)
M1

array([[ 0,  0,  1,  0,  1],
       [ 0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  1],
       [ 0, -1,  0,  0,  0]])

In [35]:
#Üst üçgen martisi
UstUcgen = np.triu(M1)
UstUcgen

array([[0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [36]:
#Alt üçgen martisi
AltUcgen = np.tril(M1)
AltUcgen

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0]])

In [38]:
M2 = np.random.randint(10,45,9).reshape(3,3)
M2

array([[37, 17, 23],
       [37, 17, 39],
       [16, 17, 16]], dtype=int32)

In [39]:
#Transpozunu alma
np.transpose(M2)

array([[37, 37, 16],
       [17, 17, 17],
       [23, 39, 16]], dtype=int32)

In [40]:
#Determinant
np.linalg.det(M2)

np.float64(-5712.0000000000055)